import Head from "next/head";
import { BackButton } from "~/components/back-button";

export default function NotRegisteredPage() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col bg-zinc-800 p-4">
        <BackButton redirectTo="/" />
        <main className="flex flex-1 flex-col items-center justify-center">
          <h1 className="text-5xl font-extrabold tracking-tight text-white">
            Não autorizado
          </h1>
          <p className="text-lg text-white">
            Você precisa entrar em contato com o admin para que ele te adicione
            aos usuários autorizados
          </p>
        </main>
      </div>
    </>
  );
}
